[build]
  command = "node src/scripts/fetch-sanity-data.js && npx eleventy"
  publish = "_site"

[build.environment]
  SANITY_PROJECT_ID = "wa7rzamu"
  SANITY_DATASET = "production"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
